project_name: hbh
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: arm
        goarm: 7
      - goarm: mips64
      - gomips: hardfloat
      - goamd64: v4
dockers:
  - image_templates:
    - "soulteary/hosts-blackhole:latest"
    - "soulteary/hosts-blackhole:{{ .Tag }}"
    dockerfile: docker/Dockerfile.gorelease
    build_flag_templates:
      - "--pull"
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/soulteary/hosts-blackhole
      - --label=org.opencontainers.image.source=https://github.com/soulteary/hosts-blackhole
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache-v2